import { p as isBlockedHostnameOrIp } from "../../ssrf-B0YaiLR8.js";
import { o as SessionEntry } from "../../types-Dj71mLx4.js";
import { v as OpenClawPluginApi } from "../../types-D_yufDi82.js";
import { _ as sleep } from "../../utils-D9cH8Yg8.js";
import { r as GatewayRequestHandlerOptions } from "../../types-Bs7khlhR.js";
import { t as definePluginEntry } from "../../plugin-entry-CAYaY4aD.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-CVQ3jYNW.js";
import { c as TtsAutoSchema, d as TtsProviderSchema, l as TtsConfigSchema, u as TtsModeSchema } from "../../zod-schema.core-BjWLrzvO.js";
import { d as isRequestBodyLimitError, m as requestBodyErrorToText, p as readRequestBodyWithLimit } from "../../http-body-DOUgvoGq.js";
export { GatewayRequestHandlerOptions, OpenClawPluginApi, SessionEntry, TtsAutoSchema, TtsConfigSchema, TtsModeSchema, TtsProviderSchema, definePluginEntry, fetchWithSsrFGuard, isBlockedHostnameOrIp, isRequestBodyLimitError, readRequestBodyWithLimit, requestBodyErrorToText, sleep };