import { i as OpenClawConfig } from "../../types.openclaw-Bg16ogQW.js";
import { t as FallbackAttempt } from "../../model-fallback.types-C_orP3Pu.js";
import { s as AuthProfileStore } from "../../types-NQxstLq5.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../../types-D_FK4icV.js";
import { t as ImageGenerationProviderPlugin } from "../../types-D_yufDi82.js";
import { n as createSubsystemLogger } from "../../subsystem-ZZYOUn60.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-CNMcnTkq.js";
import { k as normalizeGooglePreviewModelId } from "../../provider-model-shared-BQBR_XHI.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-DmTUK_xo.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../../image-generation-core-BATOk9iD.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-CLlSB2s1.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CTJfWoC8.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../../provider-registry-Bf9-29jl.js";
export { AuthProfileStore, FallbackAttempt, GeneratedImageAsset, ImageGenerationProvider, ImageGenerationProviderConfiguredContext, ImageGenerationProviderPlugin, ImageGenerationRequest, ImageGenerationResolution, ImageGenerationResult, ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };