import { i as OpenClawConfig } from "../../types.openclaw-Bg16ogQW.js";
import { t as FallbackAttempt } from "../../model-fallback.types-C_orP3Pu.js";
import { s as AuthProfileStore } from "../../types-NQxstLq5.js";
import { c as VideoGenerationProviderCapabilities, d as VideoGenerationResolution, f as VideoGenerationResult, i as VideoGenerationModeCapabilities, l as VideoGenerationProviderConfiguredContext, m as VideoGenerationTransformCapabilities, n as VideoGenerationIgnoredOverride, p as VideoGenerationSourceAsset, r as VideoGenerationMode, s as VideoGenerationProvider, t as GeneratedVideoAsset, u as VideoGenerationRequest } from "../../types-Bf15hlTe.js";
import { Un as VideoGenerationProviderPlugin } from "../../types-D_yufDi82.js";
import { n as createSubsystemLogger } from "../../subsystem-ZZYOUn60.js";
import { n as getProviderEnvVars } from "../../provider-env-vars-CNMcnTkq.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../../model-input-DmTUK_xo.js";
import { n as isFailoverError, t as describeFailoverError } from "../../failover-error-CLlSB2s1.js";
import { c as resolveCapabilityModelCandidates, f as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage } from "../../runtime-shared-CTJfWoC8.js";
import { t as parseVideoGenerationModelRef } from "../../model-ref-36MWB3ll.js";
import { n as listVideoGenerationProviders, t as getVideoGenerationProvider } from "../../provider-registry-D36w6nR3.js";
export { AuthProfileStore, FallbackAttempt, GeneratedVideoAsset, OpenClawConfig, VideoGenerationIgnoredOverride, VideoGenerationMode, VideoGenerationModeCapabilities, VideoGenerationProvider, VideoGenerationProviderCapabilities, VideoGenerationProviderConfiguredContext, VideoGenerationProviderPlugin, VideoGenerationRequest, VideoGenerationResolution, VideoGenerationResult, VideoGenerationSourceAsset, VideoGenerationTransformCapabilities, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getProviderEnvVars, getVideoGenerationProvider, isFailoverError, listVideoGenerationProviders, parseVideoGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };