import { i as OpenClawConfig } from "../../types.openclaw-Bg16ogQW.js";
import { ft as GoogleChatConfig, ut as GoogleChatAccountConfig } from "../../types.channels-DK2pcy1Z.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-dpWDaevW.js";
import { C as readStringParam, b as readReactionParams, d as createActionGate, h as jsonResult, y as readNumberParam } from "../../common-CuDT7fBi.js";
import { F as ChannelStatusIssue, y as ChannelMessageActionAdapter } from "../../types.core-DP9EvAXq.js";
import { t as ChannelMessageActionName } from "../../types.public-DtOJ3hmq.js";
import { n as PluginRuntime } from "../../types-DE9CtDzD.js";
import { o as fetchRemoteMedia } from "../../fetch-C2XlMDyv.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-hhdUoBZZ.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-C46jf9gs.js";
import { r as buildChannelConfigSchema } from "../../config-schema-Bb_36W0l.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-CVQ3jYNW.js";
import { E as resolveChannelMediaMaxBytes } from "../../media-runtime-Fulp3075.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-Dpyxvvw1.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-DWbHZixF.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-LJEtV_-N.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-x2zlKNnu.js";
import { n as resolveWebhookPath } from "../../webhook-path-D4S0EPdh.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-C6nirh5Y.js";
import { r as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-DmLIcr-H.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-3jsSCr0_.js";
import { n as loadOutboundMediaFromUrl } from "../../outbound-media-BSHxcBtV.js";
import { r as createChannelPairingController } from "../../channel-pairing-CeQS5U4X.js";
import { t as chunkTextForOutbound } from "../../text-chunking-DU1xie5Z.js";
import { d as missingTargetError } from "../../channel-feedback-BrjmK0DA.js";
import { t as extractToolSend } from "../../tool-send-esPreXeM.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-CwbWTU66.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-DH3qZPYI.js";
export { ChannelMessageActionAdapter, ChannelMessageActionName, ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, GoogleChatAccountConfig, GoogleChatConfig, GoogleChatConfigSchema, OpenClawConfig, PAIRING_APPROVED_MESSAGE, PluginRuntime, WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchRemoteMedia, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };